/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BinPage: typeof import('./src/components/BinPage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElFlex: typeof import('element-plus/es')['ElFlex']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLabel: typeof import('element-plus/es')['ElLabel']
    ElText: typeof import('element-plus/es')['ElText']
    ElTextarea: typeof import('element-plus/es')['ElTextarea']
    Home: typeof import('./src/components/Home.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitBin: typeof import('./src/components/SubmitBin.vue')['default']
  }
}
